# Generated by Django 4.1 on 2022-08-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignambassador",
            old_name="campaign_id",
            new_name="campaign",
        ),
        migrations.RenameField(
            model_name="campaignambassador",
            old_name="user_id",
            new_name="user",
        ),
    ]
