# Generated by Django 4.0.6 on 2022-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hashtag', models.CharField(max_length=20, unique=True)),
                ('img', models.ImageField(upload_to='')),
                ('campaign_type', models.CharField(choices=[('Preodic', 'Preodic'), ('Single', 'Single')], max_length=10)),
                ('start_date', models.DateField(auto_now=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('influencers_count', models.IntegerField(blank=True, null=True)),
                ('campaign_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Break', 'BRK')], max_length=10, null=True)),
                ('brand_img', models.ImageField(upload_to='')),
                ('total_posts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
