# Generated by Django 4.0.6 on 2022-08-05 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_influencer_img_user_img'),
        ('campaigns', '0002_rename_campaign_id_campaignambassador_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ambassadors',
            field=models.ManyToManyField(related_name='campaign_user', through='campaigns.CampaignAmbassador', to=settings.AUTH_USER_MODEL),
        ),
    ]
