# Generated by Django 4.0.6 on 2022-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name_alter_user_last_name'),
        ('campaigns', '0002_remove_campaign_brand_img_brand_img_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='influencer',
            field=models.ManyToManyField(blank=True, related_name='influencer_category', to='authentication.influencer'),
        ),
        migrations.AddField(
            model_name='interest',
            name='influencer',
            field=models.ManyToManyField(blank=True, related_name='influencer_interests', to='authentication.influencer'),
        ),
    ]
