# Generated by Django 4.0.6 on 2022-08-01 20:28

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_category_influencer_interest_influencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.campaigns.models.BrandImages),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.campaigns.models.CampaignImages),
        ),
    ]
