# Generated by Django 4.0.6 on 2022-08-04 09:15

import apps.campaigns.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_rename_img_brand_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, default='media/images/Brands/None/index.jpeg', upload_to=apps.campaigns.models.BrandImages),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_set', to='campaigns.brand'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='img',
            field=models.ImageField(blank=True, default='media/images/Brands/None/index.jpeg', upload_to=apps.campaigns.models.CampaignImages),
        ),
    ]
