# Generated by Django 4.0.6 on 2022-08-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_days_campaign_influencers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='days',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='influencers_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_posts',
        ),
        migrations.CreateModel(
            name='CampaignDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
