# Generated by Django 4.0.6 on 2022-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_remove_campaign_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndates',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_dates',
            field=models.ManyToManyField(blank=True, related_name='dates_set', to='campaigns.campaigndates'),
        ),
    ]
