# Generated by Django 4.0.6 on 2022-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_remove_campaigndates_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single')], max_length=10),
        ),
    ]
