# Generated by Django 4.0.6 on 2022-08-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_campaign_campaign_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_dates',
        ),
        migrations.AddField(
            model_name='campaigndates',
            name='campaign',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
    ]
