# Generated by Django 4.0.6 on 2022-08-01 20:28

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.authentication.models.InfluencerImages),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.authentication.models.UserImages),
        ),
    ]
