# Generated by Django 4.0.6 on 2022-08-10 11:51

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_influencer_img_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='img',
            field=models.ImageField(default='media/images/Brands/None/index.jpeg', upload_to=apps.authentication.models.InfluencerImages),
        ),
    ]
