# Generated by Django 4.0.6 on 2022-08-10 11:55

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_influencer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='img',
            field=models.ImageField(default='media/images/Users/None/index.jpg', upload_to=apps.authentication.models.InfluencerImages),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='media/images/Users/None/index.jpg', upload_to=apps.authentication.models.UserImages),
        ),
    ]
