# Generated by Django 4.0.6 on 2022-08-12 10:07

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_influencer_img_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='media/images/Users/None/index.png', upload_to=apps.authentication.models.UserImages),
        ),
    ]
